### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by kyamax** [kyamax/protospace-38193#1]
実装課題を提出いたします。よろしくお願いします。
#URL
[https://protospace-38193.herokuapp.com/](url)

**Comment by shodai-ito** [comment]
@kyamax さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`プロトタイプ投稿機能`**
- [x] **投稿に必要な情報が入力されていない場合は、投稿できずにそのページに留まること**
最初に投稿に失敗した場合はページにとどまりますが、連続で失敗すると下記の画面になります。
<img width="1047" alt="スクリーンショット 2022-10-01 16 02 34" src="https://user-images.githubusercontent.com/62537107/193397344-62f3948f-8431-426c-bd42-7933550e8e33.png">

### **`プロトタイプ一覧表示機能`**
- [x] **プロトタイプ毎に、画像・プロトタイプ名・キャッチコピー・投稿者名の、4つの情報について表示できること**
投稿者名の欄にコンセプトが表示されております。
<img width="1199" alt="スクリーンショット 2022-10-01 15 58 51" src="https://user-images.githubusercontent.com/62537107/193397388-d6edb9a2-74d7-487b-86c6-7a64305bd80b.png">

### **`ユーザー詳細機能`**
- [x] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
トップページのプロトタイプ投稿者名（現在はコンセプトが表示されている箇所）をクリックしても、ユーザー詳細ページに遷移できません。

- [x] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
ユーザー名が一部正しく表示されておりません。
<img width="787" alt="スクリーンショット 2022-10-01 15 57 47" src="https://user-images.githubusercontent.com/62537107/193397442-f415da31-d4e9-4aaa-8782-9e717c666ae3.png">

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by kyamax** [comment]
ご確認ありがとうございます。
修正しましたので、再度ご確認をよろしくお願いします。

**Comment by soll02solglas** [comment]
@kyamax さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
